name: southwaltoncarts_customer
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  animations: ^2.0.11
  flutter_svg: ^2.0.10+1
  pin_code_text_field: ^1.8.0
  timeline_tile: ^2.0.0
  google_fonts:
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/svg/
     - assets/fonts/


  fonts:
     - family: Raleway
       fonts:
         - asset: assets/fonts/Raleway-ExtraBold.ttf
           weight: 900
         - asset: assets/fonts/Raleway-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Raleway-Bold.ttf
           weight: 700
         - asset: assets/fonts/Raleway-Medium.ttf
           weight: 500
         - asset: assets/fonts/Raleway-Regular.ttf

